### ISSUE TITLE
#load AwsCluster.fsx throws exceptions

### ISSUE THREAD

**Issue by evilpepperman** [mbraceproject/MBrace.AWS#13]
I setup the `ProvidedKey` and saved `AwsCluster.fsx`, then did `#load "AwsCluster.fsx"` in preparation for `Config.GetCluster()`.  But during the load, I got exceptions (see below) complaining _"need updates in Vagabond"_.  Tracking the call thru the source, it seems to happen at 
`do CustomPicklers.registerCustomPicklers()` 
at `MBrace.AWS\src\MBrace.AWS\Configuration\ProcessConfiguration.fs:line 36`.

Is there a workaround, or perhaps a correction to my configuration?  Maybe this package needs to catch up to the recent work in _FsPickler_, etc?

Exception here:
```
[Loading C:\dev\mbrace-test\MBrace.StarterKit-master\packages\MBrace.AWS\MBrace.AWS.fsx
 Loading C:\dev\mbrace-test\MBrace.StarterKit-master\HandsOnTutorial.FSharp\AwsCluster.fsx]
System.TypeInitializationException: The type initializer for '<StartupCode$FSI_0002>.$FSI_0002_MBrace.AWS$fsx' threw an exception. ---> System.TypeInitializationException: The type initializer for 'MBrace.AWS.AWSWorker' threw an exception. ---> System.TypeInitializationException: The type initializer for '<StartupCode$MBrace-AWS>.$Client' threw an exception. ---> System.NotSupportedException: need updates in Vagabond
   at <StartupCode$MBrace-AWS>.$ProcessConfiguration.f@1(FSharpOption`1 workDir, Boolean populateDirs, Boolean isClientInstance, Unit unitVar0) in C:\Users\eirik.tsarpalis\devel\mbrace\MBrace.AWS\src\MBrace.AWS\Configuration\ProcessConfiguration.fs:line 36
   at MBrace.AWS.Runtime.ProcessConfiguration.initGlobalState(FSharpOption`1 workDir, Boolean populateDirs, Boolean isClientInstance) in C:\Users\eirik.tsarpalis\devel\mbrace\MBrace.AWS\src\MBrace.AWS\Configuration\ProcessConfiguration.fs:line 0
   at <StartupCode$MBrace-AWS>.$Client..cctor() in C:\Users\eirik.tsarpalis\devel\mbrace\MBrace.AWS\src\MBrace.AWS\Runtime\Client.fs:line 132
   --- End of inner exception stack trace ---
   at MBrace.AWS.AWSWorker..cctor() in C:\Users\eirik.tsarpalis\devel\mbrace\MBrace.AWS\src\MBrace.AWS\Runtime\Client.fs:line 0
   --- End of inner exception stack trace ---
   at MBrace.AWS.AWSWorker.set_LocalExecutable(String path)
   at <StartupCode$FSI_0002>.$FSI_0002_MBrace.AWS$fsx..cctor() in C:\dev\mbrace-test\MBrace.StarterKit-master\packages\MBrace.AWS\MBrace.AWS.fsx:line 22
   --- End of inner exception stack trace ---
   at <StartupCode$FSI_0002>.$FSI_0002_AwsCluster$fsx.main@() in C:\dev\mbrace-test\MBrace.StarterKit-master\HandsOnTutorial.FSharp\AwsCluster.fsx:line 29
Stopped due to error
```

**Comment by AviAvni** [comment]
@evilpepperman it's look like you tried to use custom picklers look at https://github.com/mbraceproject/MBrace.AWS/blob/2538c822f4af56b12c754e8471a7740ce29515f5/src/MBrace.AWS/Configuration/CustomPicklers.fs#L50
try not use it for now

**Comment by evilpepperman** [comment]
Ah.  But this is in the shipped `MBrace.AWS` code [`MBrace.AWS/Configuration/ProcessConfiguration.fs`](https://github.com/mbraceproject/MBrace.AWS/blob/master/src/MBrace.AWS/Configuration/ProcessConfiguration.fs), not code I wrote.  So, that's in the realm of maintainers, right?  Is there something I can do to workaround?  Note that all I'm doing is running the tutorial so far.

**Comment by AviAvni** [comment]
@evilpepperman I'll try to check how much this urgent to you?

**Comment by evilpepperman** [comment]
I'm trying to make an architectural decision on a batch parallel computing project by end-of-week.  I do appreciate your insights on this.  Currently I can't even "hello world" this tutorial (Thespian works, but that's all).  Thanks for any help.
